### ISSUE TITLE
Install option not there...

### ISSUE THREAD

**Issue by Kolhax** [magicoflolis/Magic-PH#4]
![image](https://github.com/magicoflolis/Magic-PH/assets/92904192/0aeadc0b-fd0a-4041-a829-d4da832d702c)
![image](https://github.com/magicoflolis/Magic-PH/assets/92904192/79c92795-f846-4c9b-87e6-e2b1fd6f3d1f)

**Comment by magicoflolis** [comment]
Webextension versions are current broken however the userscript version has been fixed, I will fix this issue for webextensions in future update.

https://github.com/magicoflolis/Magic-PH/releases/latest
