### ISSUE TITLE
PH script not working for me

### ISSUE THREAD

**Issue by Osahashi** [magicoflolis/Magic-PH#5]
Hey, I just can't get the script to work on PH no matter what I try, thought it might be fixed with the new version, but maybe I'm doing something wrong.

First of all, do I need anything else in addition to the script itself that needs to be installed or set up for it to work?

 - Device: Desktop
 - OS: Windows 11 Home / 23H2 Build 22631.3374
 - Browser: LibreWolf 124.0.1-1 (Firefox Build)
 - Tampermonkey: v5.1.0

What I have tried so far:
- Tampermonkey: Fix wrappedJSObject property access, Convert CDATA sections into a browser compatible format, Replace 'for each' statements, Add GM functions to this or window ON, Treat @ include like @ match, Modify existing CSP YES... 
- uBlock0 complete off

With the Debug Console, I can provide the following information:
[console-export-2024-3-27_14-45-42.txt](https://github.com/magicoflolis/Magic-PH/files/14774171/console-export-2024-3-27_14-45-42.txt)

**Comment by magicoflolis** [comment]
The userscript has been updated with code fixes and improvements you can find it here. https://github.com/magicoflolis/Magic-PH/blob/master/dist/UserJS/magicph.user.js?raw=1

In addition if you are still having trouble, please see if [ViolentMonkey](https://violentmonkey.github.io/) works better.
